# build environment
FROM node:14.16.0-alpine3.13 as build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY . ./
RUN npm start 

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]